### ISSUE TITLE
versioning of the library

### ISSUE THREAD

**Issue by lopippo** [mhoopmann/mstoolkit#10]
Greetings,

I would like to continue packaging libmstoolkit for Debian. The last version I packaged was 77. What is the present version ? I looked in the Makefile, but no version seems to be specified.
Thank you for your help.
Filippo

**Comment by mhoopmann** [comment]
The latest version is 82, which can be seen from the releases page or under the rev82 branch. I'll add version information to the readme and makefile, but for the moment these will be under the master until the next version.
Cheers,
Mike
