### ISSUE TITLE
failed compilation

### ISSUE THREAD

**Issue by lopippo** [mhoopmann/mstoolkit#11]
Greetings,
when building mstoolkit with gcc 7 I get the following errors:

src/mzParser/mz5handler.cpp: In member function 'void mzpMz5Handler::processCVParams(long unsigned int)':
src/mzParser/mz5handler.cpp:106:11: error: 'class BasicSpectrum' has no member named 'setPrecursorCharge'; did you mean 'getPrecursorCharge'?
     spec->setPrecursorCharge(atoi(cvParams_[index].value));

           ^~~~~~~~~~~~~~~~~~
           getPrecursorCharge
src/mzParser/mz5handler.cpp:109:11: error: 'class BasicSpectrum' has no member named 'setPrecursorIntensity'; did you mean 'getPrecursorIntensity'?
     spec->setPrecursorIntensity(atof(cvParams_[index].value));

           ^~~~~~~~~~~~~~~~~~~~~
           getPrecursorIntensity
src/mzParser/mz5handler.cpp:139:11: error: 'class BasicSpectrum' has no member named 'setPrecursorMZ'; did you mean 'getPrecursorMZ'?
     spec->setPrecursorMZ(atof(cvParams_[index].value));

           ^~~~~~~~~~~~~~
           getPrecursorMZ

Indeed, I cannot find setPrecursorCharge declaration anywhere. How can this be:

grep -i setPrecursorCharge * -r
src/mzParser/mz5handler.cpp:                           spec->setPrecursorCharge(atoi(cvParams_[index].value));

What am I missing here?
Thank you 
Filippo

**Comment by mhoopmann** [comment]
I perhaps fixed these things in my sandbox a few weeks ago... sorry for not notifying you sooner.

I just pulled revision 82 down and compiled on Ubuntu with GCC 7.2. Other than a bunch of annoying warning messages (sorry, will clean those up soon), compilation completed. Please let me know if you're still experiencing problems after pulling the latest revision.
