### ISSUE TITLE
Missing copyright

### ISSUE THREAD

**Issue by lopippo** [mhoopmann/mstoolkit#12]
Greetings, Michael,

I'm really sorry to bother you with these administrivia, but we need that done before uploading to Debian servers. The following file still miss copyright information:
https://github.com/mhoopmann/mstoolkit/blob/master/src/mzParser/mzMLReader.cpp
Thank you for your previous fixes.
Cheers,
Filippo

**Comment by mhoopmann** [comment]
The copyright information has been added to the file.
Cheers,
Mike
