### ISSUE TITLE
I had missed this one!!

### ISSUE THREAD

**Issue by lopippo** [mhoopmann/mstoolkit#14]
Greetings, Michael,

The debian watchdog scripts found this last file without copyright notice:
 mstoolkit/MSSingleScan/MSSingleScan.cpp
Could you please, fix it ?
Thank you for your patience...
Ciao!
Filippo

**Comment by mhoopmann** [comment]
Sure thing.
Cheers,
Mike

**Comment by lopippo** [comment]
Thanks again...
Ciao
Filippo
