### ISSUE TITLE
Compiling mstoolkit fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by sampie** [mhoopmann/mstoolkit#16]
Hi,

Trying to compile mstoolkit under ubuntu 18.04 with make -command gives following errors. It seems that library needs to be placed to the end of the compile command. See attached diff.txt for the fix.

g++ -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DGCC -DHAVE_EXPAT_CONFIG_H -I./include -lm -lpthread -ldl -L. -lmstoolkitlite MSSingleScan/MSSingleScan.cpp -o msSingleScan.shared 
/tmp/cccdX1XP.o: In function `main':
MSSingleScan.cpp:(.text+0x33): undefined reference to `MSToolkit::MSReader::MSReader()'
MSSingleScan.cpp:(.text+0x42): undefined reference to `MSToolkit::Spectrum::Spectrum()'
MSSingleScan.cpp:(.text+0x81): undefined reference to `MSToolkit::MSReader::setFilter(MSToolkit::MSSpectrumType)'
MSSingleScan.cpp:(.text+0x95): undefined reference to `MSToolkit::MSReader::addFilter(MSToolkit::MSSpectrumType)'
MSSingleScan.cpp:(.text+0xa9): undefined reference to `MSToolkit::MSReader::addFilter(MSToolkit::MSSpectrumType)'
MSSingleScan.cpp:(.text+0xbd): undefined reference to `MSToolkit::MSReader::addFilter(MSToolkit::MSSpectrumType)'
MSSingleScan.cpp:(.text+0xf9): undefined reference to `MSToolkit::MSReader::readFile(char const*, MSToolkit::Spectrum&, int)'
MSSingleScan.cpp:(.text+0x10d): undefined reference to `MSToolkit::Spectrum::getScanNumber(bool)'
MSSingleScan.cpp:(.text+0x13e): undefined reference to `MSToolkit::Spectrum::getNativeID(char*, int)'
MSSingleScan.cpp:(.text+0x156): undefined reference to `MSToolkit::Spectrum::getScanNumber(bool)'
MSSingleScan.cpp:(.text+0x18b): undefined reference to `MSToolkit::Spectrum::getScanNumber(bool)'
MSSingleScan.cpp:(.text+0x1ad): undefined reference to `MSToolkit::Spectrum::sizeMZ()'
MSSingleScan.cpp:(.text+0x1de): undefined reference to `MSToolkit::Spectrum::getNativeID(char*, int)'
MSSingleScan.cpp:(.text+0x201): undefined reference to `MSToolkit::Spectrum::getScanNumber(bool)'
MSSingleScan.cpp:(.text+0x217): undefined reference to `MSToolkit::Spectrum::getScanNumber(bool)'
MSSingleScan.cpp:(.text+0x245): undefined reference to `MSToolkit::Spectrum::sizeMZ()'
MSSingleScan.cpp:(.text+0x26d): undefined reference to `MSToolkit::Spectrum::getMZ(int)'
MSSingleScan.cpp:(.text+0x2ad): undefined reference to `MSToolkit::Spectrum::getRTime()'
MSSingleScan.cpp:(.text+0x2cd): undefined reference to `MSToolkit::Spectrum::getRTime()'
MSSingleScan.cpp:(.text+0x300): undefined reference to `MSToolkit::Spectrum::sizeZ()'
MSSingleScan.cpp:(.text+0x32a): undefined reference to `MSToolkit::Spectrum::atZ(int const&)'
MSSingleScan.cpp:(.text+0x347): undefined reference to `MSToolkit::Spectrum::atZ(int const&)'
MSSingleScan.cpp:(.text+0x39d): undefined reference to `MSToolkit::Spectrum::size()'
MSSingleScan.cpp:(.text+0x3cb): undefined reference to `MSToolkit::Spectrum::at(int const&)'
MSSingleScan.cpp:(.text+0x3f5): undefined reference to `MSToolkit::Spectrum::at(int const&)'
MSSingleScan.cpp:(.text+0x448): undefined reference to `MSToolkit::Spectrum::~Spectrum()'
MSSingleScan.cpp:(.text+0x457): undefined reference to `MSToolkit::MSReader::~MSReader()'
MSSingleScan.cpp:(.text+0x47c): undefined reference to `MSToolkit::Spectrum::~Spectrum()'
MSSingleScan.cpp:(.text+0x490): undefined reference to `MSToolkit::MSReader::~MSReader()'
collect2: error: ld returned 1 exit status
Makefile:52: recipe for target 'solib' failed
make[1]: *** [solib] Error 1
make[1]: Leaving directory '/home/sami/src/mstoolkit'
Makefile:36: recipe for target 'all' failed
make: *** [all] Error 2

[fix.txt](https://github.com/mhoopmann/mstoolkit/files/1998357/fix.txt)

**Comment by mhoopmann** [comment]
Thanks, I'll get this cleaned up next chance I get. The libraries probably built fine, but the linking to the demo application (MSSingleScan) seems to cause the problem. Linking the libraries to your application shouldn't be a problem.
