### ISSUE TITLE
Using Namespace Std in Headers

### ISSUE THREAD

**Issue by dbaileychess** [mhoopmann/mstoolkit#17]
A few of the .h files in this repo have

`using namespace std;`

Which is generally a bad practice as it causes that namespace to be used in any including file. I would suggest explicitly using the namespace when needed, and remove the `using namespace` from header files.

**Comment by mhoopmann** [comment]
Hey Derek,
No problem; was just being lazy. I might have some time to clean this up soon. But in case this is urgent, have you been using functions and values with std names (not bad practice, but perhaps not recommended)? Is there a conflict you need me to clean up ASAP?

**Comment by dbaileychess** [comment]
I was using Comet that references this package, and the C++/CLI layer had problems when trying to determine what `array` to use (cli::array or std::array). I fixed it in the Comet code by explicitly  using the correct namespace. 

So no, it isn't urgent, just wanted to give you a heads up.

**Comment by mhoopmann** [comment]
Good to hear it was fixed easily in your case. That is definitely a problem we want to avoid going forward with the next version of Comet. I should have it all squared away by then. Thanks for the notification.

**Comment by mhoopmann** [comment]
Should be fixed now. Namespaces are still in play, but locally rather than globally. Please let me know if you run into other problems. See you in November.

**Comment by dbaileychess** [comment]
looks good!
