### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by flistliu** [mhoopmann/mstoolkit#20]
Is it possible to provide compilation guide files under Windows？
Or provide Makefile file that supports nmake.
The current version is not friendly to newbies who just want to use this library on MSVC.

**Comment by mhoopmann** [comment]
Yes, I can do that and will post something for you in a few days. Sorry for the delay.

**Comment by mhoopmann** [comment]
Ack. I was far slower than a few days. MAKEFILE.nmake was added to the source tree. It can be used to compile with nmake, provided you use the x64 Native Tools Command Prompt. This should be included with your MSVC developer tools. I've tested with MSVC 2019 and it works well on my end.

The makefile isn't very smart: it will recompile everything even if you change only one file. So feel free to expand upon it for your needs. Or, ideally, use it as a template to build your own MSVC solution. Please let me know if there are any problems.
