### ISSUE TITLE
MGF support, it's write-only but not read-only

### ISSUE THREAD

**Issue by shengqh** [mhoopmann/mstoolkit#5]
The introduction indicated that MSToolKit supported the MGF read-only but in the code, it was actually MGF write-only. I didn't find the code for MGF reading in MSReader class.

Best,

Quanhu Sheng

**Comment by mhoopmann** [comment]
Support for MGF reading was temporarily suspended and the readme failed to reflect this. Support for MGF reading has been added back and support to remain compatible has resumed.
