### ISSUE TITLE
Is is possible to add a flag to choose whether .RAW format is enabled or not

### ISSUE THREAD

**Issue by kagami-c** [mhoopmann/mstoolkit#7]
I'm trying to compile MSToolkit under Visual Studio Community 2015, and I don't have a Thermo RAW File Reader Library. To make compiling success, I try to modify some codes to make it independent on XRawfile library. My modification is attached below (patch.txt) by adding a new flag _ENABLE_RAW besides single _MSC_VER flag. If you think that this is a good idea, could you have a check on whether these modifications are practical or not. I have successfully compiled it on Release configuration. (Since I'm new to this library, I'm not familiar with all features provided by it) Thank you very much! 
[patch.txt](https://github.com/mhoopmann/mstoolkit/files/90275/patch.txt)

**Comment by mhoopmann** [comment]
Thanks much, I will improve the RAW file reader handling.

**Comment by mhoopmann** [comment]
I chose to use an opt-out flag because I do want to encourage supporting Thermo RAW on windows builds.

Simply add _NO_THERMORAW to your build flags and you should be good to go. This will apply to all future updates. Thanks again for the suggestion!
